/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LivreDuConducteurRouteImport } from './routes/livre-du-conducteur'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as CantiqueNumeroRouteImport } from './routes/cantique.$numero'
import { Route as ListeIdRouteImport } from './routes/liste.$id'
import { Route as RecueilLangueRouteImport } from './routes/recueil.$langue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreDuConducteurRoute = LivreDuConducteurRouteImport.update({
  id: '/livre-du-conducteur',
  path: '/livre-du-conducteur',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const CantiqueNumeroRoute = CantiqueNumeroRouteImport.update({
  id: '/cantique/$numero',
  path: '/cantique/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeIdRoute = ListeIdRouteImport.update({
  id: '/liste/$id',
  path: '/liste/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecueilLangueRoute = RecueilLangueRouteImport.update({
  id: '/recueil/$langue',
  path: '/recueil/$langue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/livre-du-conducteur': typeof LivreDuConducteurRoute
  '/parametres': typeof ParametresRoute
  '/cantique/$numero': typeof CantiqueNumeroRoute
  '/liste/$id': typeof ListeIdRoute
  '/recueil/$langue': typeof RecueilLangueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/livre-du-conducteur': typeof LivreDuConducteurRoute
  '/parametres': typeof ParametresRoute
  '/cantique/$numero': typeof CantiqueNumeroRoute
  '/liste/$id': typeof ListeIdRoute
  '/recueil/$langue': typeof RecueilLangueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/livre-du-conducteur': typeof LivreDuConducteurRoute
  '/parametres': typeof ParametresRoute
  '/cantique/$numero': typeof CantiqueNumeroRoute
  '/liste/$id': typeof ListeIdRoute
  '/recueil/$langue': typeof RecueilLangueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/aide'
    | '/auth'
    | '/livre-du-conducteur'
    | '/parametres'
    | '/cantique/$numero'
    | '/liste/$id'
    | '/recueil/$langue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/aide'
    | '/auth'
    | '/livre-du-conducteur'
    | '/parametres'
    | '/cantique/$numero'
    | '/liste/$id'
    | '/recueil/$langue'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/aide'
    | '/auth'
    | '/livre-du-conducteur'
    | '/parametres'
    | '/cantique/$numero'
    | '/liste/$id'
    | '/recueil/$langue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AideRoute: typeof AideRoute
  AuthRoute: typeof AuthRoute
  LivreDuConducteurRoute: typeof LivreDuConducteurRoute
  ParametresRoute: typeof ParametresRoute
  CantiqueNumeroRoute: typeof CantiqueNumeroRoute
  ListeIdRoute: typeof ListeIdRoute
  RecueilLangueRoute: typeof RecueilLangueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livre-du-conducteur': {
      id: '/livre-du-conducteur'
      path: '/livre-du-conducteur'
      fullPath: '/livre-du-conducteur'
      preLoaderRoute: typeof LivreDuConducteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cantique/$numero': {
      id: '/cantique/$numero'
      path: '/cantique/$numero'
      fullPath: '/cantique/$numero'
      preLoaderRoute: typeof CantiqueNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liste/$id': {
      id: '/liste/$id'
      path: '/liste/$id'
      fullPath: '/liste/$id'
      preLoaderRoute: typeof ListeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recueil/$langue': {
      id: '/recueil/$langue'
      path: '/recueil/$langue'
      fullPath: '/recueil/$langue'
      preLoaderRoute: typeof RecueilLangueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AideRoute: AideRoute,
  AuthRoute: AuthRoute,
  LivreDuConducteurRoute: LivreDuConducteurRoute,
  ParametresRoute: ParametresRoute,
  CantiqueNumeroRoute: CantiqueNumeroRoute,
  ListeIdRoute: ListeIdRoute,
  RecueilLangueRoute: RecueilLangueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
